/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.jmlb23.todo.server

import com.github.jmlb23.todo.server.impl.TodoService
import com.github.jmlb23.todo.server.repositories.InMemoryTodoRepository
import io.grpc.netty.NettyServerBuilder

fun main(args: Array<String>) {
    val repo = InMemoryTodoRepository()
    val server = NettyServerBuilder.forPort(5000).addService(TodoService(repo)).build()

    server.start()
    server.awaitTermination()
}
